### PR TITLE
Fix typo and missing initializer

### PR DESCRIPTION
**Pull request by DK1DA**
Had to fix this before I was able to deploy it on my service.

Also I've written a little sample app to deploy it right away, will need a new blackfish release though before it's working: https://github.com/kimar/blackfish-example/tree/master

### CODE REVIEW

**Comment by elliottminns** [comment]
Thanks! Much appreciated.

**Comment by DK1DA** [comment]
You're welcome @elliottminns. Could you also please tag a new version? My sample still tries to pull the old one. I've created an overview on frameworks and apps being supported by my PaaS here: https://github.com/SwiftOnMe/running-on-me

**Comment by elliottminns** [comment]
Force updated the tag, your changes are still in 0.1.1, i'll start on some proper tests to prevent any issues like this again. I shall also check out your PaaS.

**Comment by DK1DA** [comment]
Awesome, it's running now: http://nostalgic-hoover.serve.swifton.me/
Thx a bunch buddy! :+1:

**Pull request merged**
